CREATE TABLE clientes (
      id BIGINT AUTO_INCREMENT PRIMARY KEY,
      rut VARCHAR(12) NOT NULL UNIQUE,
      nombre VARCHAR(255) NOT NULL,
      email VARCHAR(255) NOT NULL UNIQUE,
      elefono VARCHAR(50)
);
